---

- name: "configuration backend play." 
  hosts: all
  user: ubuntu
  gather_facts: false

  environment:
    # ID: "{{ lookup( 'env', 'CIRCLE_WORKFLOW_ID:0:7' )}}"
    ID: WorkflowID
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy
