---
- name: "upgrade packages."
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install zip utility."
  apt:
    name: [ "zip", "unzip" ]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present