Description: >
  UdaPeople backend stack.

Parameters:
  ID: 
    Description: Unique ID
    Type: String
    Default: "${CIRCLE_WORKFLOW_ID:0:7}"
    
Resources:
  
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "UdaPeopleSecurity-${ID}"
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity 
      ImageId: ami-0d382e80be7ffdae5
      Tags:
        - Key: Name
          Value: !Sub "backend-${ID}"

Outputs:
  EC2PublicDNS:
    Description: 'Public DNS of EC2 instance'
    Value: !GetAtt EC2Instance.PublicDnsName
    # Export:
    #   Name: !Sub "${AWS::PublicDnsName}"
  
  EC2PublicIP:
    Description: Public EC2Instance IP for references
    Value: !GetAtt EC2Instance.PublicIp
    # Export:
    #   Name: !Sub "${AWS::PublicIpAddress}"

    